services:
  database:
    container_name: database-secure
    build: ./database
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=CommunicationLTD
    ports:
      - "3306:3306"
  web:
    container_name: web-secure
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - database
    user: root
    command: /bin/bash -c "python backend.py"